# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('num_of_chapters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('chapter_of_death', models.IntegerField(default=0)),
                ('manner_of_death', models.CharField(choices=[('Age', 'AGE'), ('Animal', 'ANIMAL'), ('Arrow/bolt', 'ARROW/BOLT'), ('Asphyxiation', 'ASPHYXIATION'), ('Beheading', 'BEHEADING'), ('Childbirth', 'CHILDBIRTH'), ('Crushing', 'CRUSHING'), ('Dark magic', 'DARKMAGIC'), ('Drowning', 'DROWNING'), ('Falling', 'FALLING'), ('Fire', 'FIRE'), ('Hanging', 'HANGING'), ('Head trauma', 'HEADTRAUMA'), ('Illness', 'ILLNESS'), ('Impalement', 'IMPALEMENT'), ('Poisoning', 'POISONING'), ('Slain (axe)', 'SLAINAXE'), ('Slain (mace)', 'SLAINMACE'), ('Slain (sword)', 'SLAINSWORD'), ('Slain (scythe)', 'SLAINSCYTHE'), ('Stabbing', 'STABBING'), ('Starvation', 'STARVATION'), ('Throat cut', 'THROATCUT'), ('Unknown', 'UNKNOWN'), ('White Walkers/Wights/Others', 'WHITEWALKERSWIGHTSOTHERS'), ('Wound infection', 'WOUNDINFECTION')], default='Unknown', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Unknown', 'UNKNOWN')], default='Unknown', max_length=7)),
                ('is_nobility', models.BooleanField(default=False)),
                ('book_of_death', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='character_deaths', to='asoiaf.Book')),
            ],
        ),
    ]
