# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoiaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='book_of_death',
            field=models.IntegerField(default=0),
        ),
    ]
