# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoiaf', '0002_auto_20190408_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='book_of_death',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='character_deaths', to='asoiaf.Book'),
        ),
    ]
