# Generated by Django 2.2 on 2019-04-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoiaf', '0003_auto_20190408_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter_of_Death',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character')),
                ('chapter_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character')),
                ('manner_of_death', models.CharField(choices=[('Age', 'AGE'), ('Animal', 'ANIMAL'), ('Arrow/bolt', 'ARROW/BOLT'), ('Asphyxiation', 'ASPHYXIATION'), ('Beheading', 'BEHEADING'), ('Childbirth', 'CHILDBIRTH'), ('Crushing', 'CRUSHING'), ('Dark magic', 'DARKMAGIC'), ('Drowning', 'DROWNING'), ('Falling', 'FALLING'), ('Fire', 'FIRE'), ('Hanging', 'HANGING'), ('Head trauma', 'HEADTRAUMA'), ('Illness', 'ILLNESS'), ('Impalement', 'IMPALEMENT'), ('Poisoning', 'POISONING'), ('Slain (axe)', 'SLAINAXE'), ('Slain (mace)', 'SLAINMACE'), ('Slain (sword)', 'SLAINSWORD'), ('Slain (scythe)', 'SLAINSCYTHE'), ('Stabbing', 'STABBING'), ('Starvation', 'STARVATION'), ('Throat cut', 'THROATCUT'), ('Unknown', 'UNKNOWN'), ('White Walkers/Wights/Others', 'WHITEWALKERSWIGHTSOTHERS'), ('Wound infection', 'WOUNDINFECTION')], default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nobility',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character')),
                ('house', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='book_of_death',
        ),
        migrations.RemoveField(
            model_name='character',
            name='chapter_of_death',
        ),
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_nobility',
        ),
        migrations.RemoveField(
            model_name='character',
            name='manner_of_death',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Book_of_Death',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoiaf.Book')),
            ],
        ),
    ]
