# Generated by Django 2.2 on 2019-04-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoiaf', '0005_auto_20190410_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deaths',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character'),
        ),
        migrations.AlterField(
            model_name='nobility',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asoiaf.Character'),
        ),
    ]
