# Generated by Django 2.2 on 2019-04-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoiaf', '0006_auto_20190410_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deaths',
            new_name='Death',
        ),
    ]
